version: "3"
services:
  hub:
    image: selenium/hub:4.1.1-20211217
    container_name: hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  edge1:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge1_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge1
    environment:
      - DISPLAY_CONTAINER_NAME=edge1
      - FILE_NAME=edge1_video_test.mp4

  edge2:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge2_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge2
    environment:
      - DISPLAY_CONTAINER_NAME=edge2
      - FILE_NAME=edge2_video_test.mp4

  edge3:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge3_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge3
    environment:
      - DISPLAY_CONTAINER_NAME=edge3
      - FILE_NAME=edge1_video_test.mp4

  edge4:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge4_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge4
    environment:
      - DISPLAY_CONTAINER_NAME=edge4
      - FILE_NAME=edge2_video_test.mp4

  edge5:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge5_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge5
    environment:
      - DISPLAY_CONTAINER_NAME=edge5
      - FILE_NAME=edge1_video_test.mp4

  edge6:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  edge6_video:
    image: selenium/video:ffmpeg-4.3.1-20211217
    volumes:
      - C:\tmp\videos:/videos
    depends_on:
      - edge6
    environment:
      - DISPLAY_CONTAINER_NAME=edge6
      - FILE_NAME=edge2_video_test.mp4

